source 'https://rubygems.org'

ruby '2.7.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '6.1.0'
gem 'rails_12factor', group: :production
gem 'pg', group: :production
gem 'unicorn' # see: https://devcenter.heroku.com/articles/ruby-default-web-server
gem "unicorn-rails"
gem 'rack-timeout'

# Use sqlite3 as the database for Active Record
gem 'sqlite3', group: :development

# Use SCSS for stylesheets
gem 'sass-rails', '~> 6.0.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.2.2'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-ui-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

gem 'pry', '0.13.1'  # todo: fix the fact that the rack-web-console's Gemfile spec to have version 0.9.10 load here.  Maybe add_runtime_dependancy is bad?
gem 'rack-webconsole-pry', :require => 'rack-webconsole'
# gem 'opal-rails'

# gem 'codemirror-rails'
gem "twitter-bootstrap-rails" # need to run: rails generate bootstrap:install static

gem 'github_api'
gem 'omniauth'
gem 'omniauth-github'
gem 'high_voltage', '~> 3.0.0'
# gem 'redcarpet', '~> 3.5.1'
