/* Generated by Opal 0.6.3 */
(function($opal) {
  var self = $opal.top, $scope = $opal, nil = $opal.nil, $breaker = $opal.breaker, $slice = $opal.slice, $klass = $opal.klass;

  $opal.add_stubs(['$*', '$second', '$minute', '$hour', '$day', '$week', '$-', '$now', '$+', '$from']);
  return (function($base, $super) {
    function $Numeric(){};
    var self = $Numeric = $klass($base, $super, 'Numeric', $Numeric);

    var def = self._proto, $scope = self._scope;

    def.$second = function() {
      var self = this;

      return self;
    };

    def.$minute = function() {
      var self = this;

      return (60)['$*'](self.$second());
    };

    def.$hour = function() {
      var self = this;

      return (60)['$*'](self.$minute());
    };

    def.$day = function() {
      var self = this;

      return (24)['$*'](self.$hour());
    };

    def.$week = function() {
      var self = this;

      return (7)['$*'](self.$day());
    };

    def.$month = function() {
      var self = this;

      return (4)['$*'](self.$week());
    };

    def.$ago = function() {
      var self = this;

      return $scope.Time.$now()['$-'](self);
    };

    def.$until = function(time) {
      var self = this;

      return time['$-'](self);
    };

    def.$from = function(time) {
      var self = this;

      return time['$+'](self);
    };

    def.$from_now = function() {
      var self = this;

      return self.$from($scope.Time.$now());
    };

    $opal.defn(self, '$seconds', def.$second);

    $opal.defn(self, '$minutes', def.$minute);

    $opal.defn(self, '$hours', def.$hour);

    $opal.defn(self, '$days', def.$day);

    $opal.defn(self, '$weeks', def.$week);

    return $opal.defn(self, '$minutes', def.$minute);
  })(self, null)
})(Opal);
